# Generated by Django 3.0.9 on 2020-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(null=True),
        ),
    ]
