# Generated by Django 3.0.9 on 2020-08-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20200805_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(max_length=300),
        ),
    ]
